[package]
name = "winvcon"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.13", features = ["derive", "cargo"] }
windows = { version = "0.58.0", features = ["Win32_System_Console"] }
